spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123
    url: jdbc:mysql://localhost:3306/information_system?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
  mail:
    password: vpdkyqhwbhbobffd
    username: 804738464@qq.com
    default-encoding: utf-8
    host: smtp.qq.com
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  messages:
    basename: i18n.studentlogin
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123
mybatis:
  config-location: classpath:mybatis/sqlmapper.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

logging:
  level:
    leslie.information_system.mapper: debug
